// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl38YAYBqVxN-z9R3g9Sn_dkjnkprCUQk',
    appId: '1:391777610007:web:ab04143c4389518b1eef52',
    messagingSenderId: '391777610007',
    projectId: 'fir-flutter-codelab-327e5',
    authDomain: 'fir-flutter-codelab-327e5.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-327e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2dcvgzNRYQtytzFjNcIhwJ8PBZC__08',
    appId: '1:391777610007:android:a3742ddff9df479f1eef52',
    messagingSenderId: '391777610007',
    projectId: 'fir-flutter-codelab-327e5',
    storageBucket: 'fir-flutter-codelab-327e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ED4jfDnwq7kuoMWwFWN4RPBrah56ymg',
    appId: '1:391777610007:ios:5aee41d7c93945cf1eef52',
    messagingSenderId: '391777610007',
    projectId: 'fir-flutter-codelab-327e5',
    storageBucket: 'fir-flutter-codelab-327e5.appspot.com',
    iosClientId: '391777610007-lr5722th5t9n55ke1fbdhsdvacnt5kto.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ED4jfDnwq7kuoMWwFWN4RPBrah56ymg',
    appId: '1:391777610007:ios:5aee41d7c93945cf1eef52',
    messagingSenderId: '391777610007',
    projectId: 'fir-flutter-codelab-327e5',
    storageBucket: 'fir-flutter-codelab-327e5.appspot.com',
    iosClientId: '391777610007-lr5722th5t9n55ke1fbdhsdvacnt5kto.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
